page-web-schooler
proxima-cm/proxima-cm.github.io pull request #8
Opened 2022-10-16 17:01 UTC by Ab0698

Creation de la page web schooler

2022-10-17 19:25 UTC, abdounasser202 requested changes

2022-10-17 19:25 UTC, abdounasser202 commented on schooler.html
> +    <title>Proxima Technologies Cameroon - We make softwares for you</title>
Remplacer le contenu de la balise title par Schooler, logiciel de gestion des établissements scolaire au Cameroun

Cette title va permettre le référencement google si quelqu'un tape logiciel de gestion scolaire

2022-10-17 19:25 UTC, abdounasser202 commented on schooler.html
> +    <meta name="description" content="Proxima est une SSII situé à Douala - Cameroun.
la balise meta description doit avoir toute la description du logiciel par exemple: ADMINSTRATION DES ELEVES & ENSEIGNANTS, GESTION FINANCIERE ET COMPTABLE , COMMUNICATION mais faut bien écrire en bon français

2022-10-17 19:25 UTC, abdounasser202 commented on schooler.html
> +                <button class="btn btn-cta proxima-btn" type="button" data-toggle="modal" data-target="#modal-contact" data-backdrop="static">EN SAVOIR PLUS</button>
Le bouton ci ne renvoie aucun contenu, il faut corriger ça

2022-10-17 19:26 UTC, abdounasser202 commented
@Ab0698 il faut revoir nos commentaires

@elmaroufa  et moi allons te donner plus d'amples informations

2022-10-30 14:35 UTC, franklinlemaire commented
Bonsoir à tous par rapport, M. @Ab0698 voici mes propositions par rapport à Schooler:

1- Il faut essayer de corriger la faute sur "acceuil" ensuite augmenter les tailles des caractères du menu;
2- Le bouton "En savoir plus" doit interagir comme celui de la page index.html ou à défaut le retirer;
3- Corriger les fautes du titre et tout le paragraphes "Que ce que schooler?";
4- Remplacer "Que ce qui fait schooler?" par "Nos services";
5- Corriger les fautes de ces différents services;
6- Remplacer "Produits" par "Autres produits" et les citer (ALPHADSF, BAKER et PROXIMASMS)

**Nb:**  l'idéal est d'écrire "Qu'est ce que" au lieu de "Que ce que" .
Merci pour la compréhension

2023-02-01 10:53 UTC, abdounasser202 commented on schooler.html
> +    <title>Proxima Technologies Cameroon - We make softwares for you</title>
done

2023-02-01 10:53 UTC, abdounasser202 commented on schooler.html
> +                <button class="btn btn-cta proxima-btn" type="button" data-toggle="modal" data-target="#modal-contact" data-backdrop="static">EN SAVOIR PLUS</button>
done

2023-02-01 10:53 UTC, merged